Optimize #823 development cleaning
ExploreASL/ExploreASL pull request #1074
Opened 2022-01-31 12:39 UTC by jan-petr

### Linked issue

#823. Agreed with all comments. New `Development` folder under functions will be created in an issue #1073 - it needs a new issues, because we also need to adapt the documentation and folder initialization etc.

2022-01-31 19:07 UTC, HenkMutsaerts requested changes
We should give the good example to the kids, "clean develop folder" is not really a specific commit title. "Clean develop: delete study config files" would be better.

I don't understand why we make a list in a single issue and then only do 1 item from this list ;)

The docu functionality needs to be improved anyway, as we discussed this morning, so why not moving the other development files to the new folder in this issue, and updating the docu files in this issue as well? Splitting issues for real functional differences is good but spreading too thin in this case imho.

BTW: we should adapt the docu crawling, that it doesn't crawl across a fixed number of folders but across all folders inside `/Functions`, then we don't have to change the docu crawler function for each time we add a new folder to `/Functions`.

2022-02-01 08:38 UTC, MichaelStritt commented
> We should give the good example to the kids, "clean develop folder" is not really a specific commit title. "Clean develop: delete study config files" would be better:)

The kids are fine with it 👍

2022-02-02 13:05 UTC, jan-petr commented
The list was to start the discussion - so a part was done (several things), a part will be done in a different issue, part I found out doesn't need to be done.

2022-02-07 09:17 UTC, HenkMutsaerts approved these changes

2022-02-08 18:18 UTC, merged