Closes #577 bug #577 population sessions
ExploreASL/ExploreASL pull request #1346
Opened 2023-03-18 06:24 UTC by HenkMutsaerts

### Linked issue

Closes #577

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

2023-03-18 06:27 UTC, HenkMutsaerts commented
@MDijsselhof Can you test this in your dataset(s) by rerunning the population module? The first columns in the stats files are created from `participants.tsv`, which is why you should first remove `participants.tsv`. Now `participants.tsv` should be created correctly and the rest should follow.

2023-03-18 09:05 UTC, jan-petr requested changes
Some minor formal things to be fixed.

2023-03-18 09:05 UTC, jan-petr commented on Functions/Administration/xASL_adm_GetPopulationSessions.m
> +    SESSIONS = sort(unique(NewList)); % determine unique session numbers
We have to be very careful about sorting! Because when sorting strings, ASL_12 will come before ASL_2, but we want to sort by the number - so ASL_12 after ASL_2

2023-03-18 09:05 UTC, jan-petr commented on Functions/Administration/xASL_adm_GetPopulationSessions.m
> +    SESSIONS = sort(unique(NewList)); % determine unique session numbers
You have to sort as number not as string. Or perhaps this won't matter later in the code, but then the sorting might not be necessary. My point - if you need to sort, then you better do it properly ;)

2023-03-18 09:05 UTC, jan-petr commented on Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m
> +        TempSessionNames = sort(unique(DataIn(:,2)))';
again - careful how you sort.

2023-03-18 09:05 UTC, jan-petr commented on Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m
> +        MatrixOut(1, 1) = MatrixIn(1, 1); % subject header
careful -  you are using different brackets on each line. It is probably fine as MatrixIn has cells. I'm just asking to double check and you can then resolve without answering ;)

2023-03-18 09:05 UTC, jan-petr commented on Functions/ImageProcessing/xASL_im_SplitImageLabels.m
>  % FORMAT: xASL_im_SplitImageLabels(ImagePaths, LabelTable[, OutputFolder, bOverwrite, ResampleDir, SubRegExp])
please add the new variable to this line as well

2023-03-18 10:05 UTC, HenkMutsaerts commented on Functions/Administration/xASL_adm_GetPopulationSessions.m
> +    SESSIONS = sort(unique(NewList)); % determine unique session numbers
Good point. At this time, nobody probably has used >9 sessions, Mathijs could have for NOMARED, would be good to check. I fixed this throughout now.

2023-03-23 18:27 UTC, jan-petr approved these changes
OK.

2023-03-28 07:43 UTC, MDijsselhof commented on Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m
> +% FORMAT: xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x[, bOverwrite])
Should it be like this? With the [ ]?

2023-03-28 07:45 UTC, MDijsselhof requested changes
I had one small question

2023-03-28 08:48 UTC, jan-petr commented on Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m
> +% FORMAT: xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x[, bOverwrite])
Yes. This is correct. Not in the real function declaration. But in the comment, it specifies that the parameters in [ ] are optional. So correct in this case - we do it like this in almost all other functions.

2023-03-28 09:25 UTC, MDijsselhof approved these changes

2023-03-28 09:27 UTC, merged