Bug #1411 fix multi tem0
ExploreASL/ExploreASL pull request #1412
Opened 2023-05-15 20:32 UTC by jan-petr

### Linked issue

Close #1411

2023-05-17 15:39 UTC, HenkMutsaerts requested changes
Here, we assume that the shortest TE of both ASL and M0 is the one that should be equal between both, is that always the case?

E.g., if we have M0_TE = [10 20 30] and ASL_TE = 20, then we will have a problem.
So I would do the following:

1) establish the ASL_TE
2) establish the M0_TE
3) check which ones are overlapping
4) use the smallest value of those that are overlapping (3)
5) issue warning if the smallest overlapping value differs from the smallest ASL OR smallest M0 TE value

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +			minTE = min(uniqueNonzeroTE);
code says smallest, but comment says positive and non-zero? (which was selected on the previous sentence)

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +			imM0 = mean(imM0(:,:,:,jsonM0.EchoTime == minTE), 4);
this should be the nanmean instead of mean.

Also, should we always do the shortest? And not the one closest to ASL?

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +imM0 = mean(imM0,4);
nanmean instead (because there may have been motion correction of M0 which gives some NaNs outside the FoV)

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +imM0 = mean(imM0,4);
space behind the comma (code styleguide)

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_Quantify.m
> +ASLshortestTE = [];
If the EchoTime field doesn't exist, this will create an error?
We need at least to add a warning below, if we need to do the M0 correction by T2 star and we don't know the `ASLshortestTE`

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_Quantify.m
> +    if  ~isempty(ASLshortestTE) && ~isempty(M0shortestTE)
`else warning` missing

2023-05-17 15:39 UTC, HenkMutsaerts commented on Modules/SubModule_ASL/xASL_wrp_Quantify.m
> +			% If the shortest TEs are unequal, then we have to compensate for this
This is the problem. Here, we assume that the shortest TE of both ASL and M0 is the one that should be equal between both, is that always the case?

E.g., if we have M0_TE = [10 20 30] and ASL_TE = 20, then we will have a problem.
So I would do the following:

1) establish the ASL_TE
2) establish the M0_TE
3) check which ones are overlapping
4) use the smallest value of those that are overlapping (3)
5) issue warning if the smallest overlapping value differs from the smallest ASL OR smallest M0 TE value

2023-05-19 14:22 UTC, BeatrizPadrela approved these changes

2023-05-19 15:16 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +			minTE = min(uniqueNonzeroTE);
Code has two parts - first selecting non-zero positive. and then selecting smallest of those. 
So all good and consistent, but I will fine-tune the comments.

2023-05-19 15:20 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +			imM0 = mean(imM0(:,:,:,jsonM0.EchoTime == minTE), 4);
Closest to ASL = we deal with that in reporting discrepancies. nanmean - implemented now.

2023-05-19 15:21 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +imM0 = mean(imM0,4);
yes. done.

2023-05-19 15:22 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
> +imM0 = mean(imM0,4);
done.

2023-05-19 15:28 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_Quantify.m
> +ASLshortestTE = [];
Good point. Adding errors on non-existeng TEs when needed.

2023-05-19 15:29 UTC, jan-petr commented on Modules/SubModule_ASL/xASL_wrp_Quantify.m
> +    if  ~isempty(ASLshortestTE) && ~isempty(M0shortestTE)
Added

2023-05-19 15:32 UTC, merged