Bug #151 minor bugfixes
ExploreASL/ExploreASL pull request #152
Opened 2020-09-24 13:57 UTC by HenkMutsaerts

Found these minor fixes when working with TopUp

2020-09-24 14:42 UTC, jan-petr approved these changes
Looks good. Can be merged.

2020-09-24 17:36 UTC, HenkMutsaerts commented
Sorry, added the latest commit for you to review

2020-09-24 19:19 UTC, jan-petr requested changes
xASL_module_ASL.m 
line 282 - the edits on all three lines have to be reverted.

This loading of x, outputting x by the register function and saving x was there so that we can save the TC for the visual QC - that was a part of a previously approved branch.

In the future, we will not save it through X, but directly to the JSON-QC file, but we are not yet there, so this edit has to be reverted.

If you agree, I can do that, but wanted to reach a consensus on that first :)

2020-09-25 10:06 UTC, jan-petr approved these changes

2020-09-25 10:09 UTC, merged