Feature #1655 new isnear
ExploreASL/ExploreASL pull request #1657
Opened 2024-03-26 13:41 UTC by jan-petr

### Linked issue

Close #1655

2024-03-27 03:00 UTC, HenkMutsaerts requested changes
Minor stuff.
More importantly: I would tweak nomenclature so it is less obvious that this is a copy of the original. E.g., 

x -> inputA (or a)
y -> inputB (or b)
tol -> tolerance

isnear -> approximates OR isCloseBy OR isNearby

2024-03-27 03:00 UTC, HenkMutsaerts commented on Functions/Statistics/xASL_stat_Isnear.m
> +   tol=1e-8;
needs a space

2024-03-27 03:00 UTC, HenkMutsaerts commented on Functions/Statistics/xASL_stat_Isnear.m
> +	error('Input TOL must have the same size as X or Y or be a scalar');
I would turn the error around 1) tol needs to be a scalar (default) OR 2) tol has equal size (exotic version)

2024-03-27 03:00 UTC, HenkMutsaerts commented on Functions/Statistics/xASL_stat_Isnear.m
> +   tol=1e-8;
Also, should the default tolerance not be eps? That seems less arbitrary? Or is eps 1^e-8 :)

2024-03-27 08:35 UTC, jan-petr commented on Functions/Statistics/xASL_stat_Isnear.m
> +   tol=1e-8;
I removed EPS to remove similarities. So 1e-8 is the value isnear was really using.
Space added.

2024-03-27 08:38 UTC, jan-petr commented
> Minor stuff. More importantly: I would tweak nomenclature so it is less obvious that this is a copy of the original. E.g.,
> 
> x -> inputA (or a) y -> inputB (or b) tol -> tolerance
I use X and Y because the original used A and B :)
tol is a common keyword, so no need to use tolerance.
 
> isnear -> approximates OR isCloseBy OR isNearby
Agree, but those names sound lame. I would use "IsEqualTol"

2024-03-27 08:42 UTC, jan-petr commented on Functions/Statistics/xASL_stat_Isnear.m
> +	error('Input TOL must have the same size as X or Y or be a scalar');
Done

2024-03-28 09:42 UTC, HenkMutsaerts approved these changes

2024-03-28 10:36 UTC, merged