#1711 xASL_module_ASL: for 3D spiral 0->NaN
ExploreASL/ExploreASL pull request #1756
Opened 2024-08-26 10:50 UTC by HenkMutsaerts

### Linked issue

Required: mention the issue number of the linked feature or bug here

### How to test

### Comments

See issue, please check if you like the current location where I do this. I don't think we should change this for the BIDS conversion, this is an image processing issue.

2024-08-27 12:13 UTC, jan-petr requested changes
Minor comment.

2024-08-27 12:13 UTC, jan-petr commented on Modules/xASL_module_ASL.m
> +if strcmpi(x.Q.Vendor, 'GE') && strcmpi(x.Q.MRAcquisitionType, '3D') && strcmpi(x.Q.PulseSequenceType, 'spiral')
GE should be regexpi - cause we might have GE_wip.

2024-08-30 10:13 UTC, HenkMutsaerts commented on Modules/xASL_module_ASL.m
> +if strcmpi(x.Q.Vendor, 'GE') && strcmpi(x.Q.MRAcquisitionType, '3D') && strcmpi(x.Q.PulseSequenceType, 'spiral')
changed to "contains"

2024-08-30 12:18 UTC, jan-petr approved these changes
OK.

2024-08-30 12:20 UTC, merged