Hotfix #578
ExploreASL/ExploreASL pull request #582
Opened 2021-05-15 11:23 UTC by HenkMutsaerts

### Linked issue

Closes #578 and to create release 1.6.1

2021-05-15 11:29 UTC, MDijsselhof approved these changes

2021-05-15 11:40 UTC, BeatrizPadrela approved these changes
seems ok!

2021-05-15 19:59 UTC, jan-petr approved these changes
Ready to release...

2021-05-15 19:59 UTC, jan-petr commented
Sorry - my last commit wasn't signed... Will fix that.

2021-05-17 09:26 UTC, MichaelStritt requested changes
### GE_PCASL_3Dspiral_volunteer

```matlab
>> source = '.\New_TestData\GE_PCASL_3Dspiral_volunteer\sourceStructure.json';
>> [x] = ExploreASL_Master(source,1,1);

...

ExploreASL will run the import workflow and will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...rver_xASL\New_TestData\GE_PCASL_3Dspiral_volunteer\sourceStructure.json
Import Modules      DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.6.1 initialized ... 

...

K>> x.DataParPath

ans =

    '.\New_TestData\GE_PCASL_3Dspiral_volunteer\sourceStructure.json'

Error using xASL_imp_BIDS2Legacy (line 30)
Input argument should be dataset_description.json, invalid input

Error in ExploreASL_ImportMaster (line 43)
                    x = xASL_imp_BIDS2Legacy(x);

Error in ExploreASL_Master (line 74)
    x = ExploreASL_ImportMaster(x);
```

2021-05-17 09:44 UTC, MichaelStritt commented on Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
> +    [Fpath, Ffile, Fext] = fileparts(x.DataParPath);
Check out my changes in b4706bd

2021-05-17 11:12 UTC, MichaelStritt commented on Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
> +    [Fpath, Ffile, Fext] = fileparts(x.DataParPath);
```
================================= TEST RESULTS =================================

              name                  unit          tests        passed
    _________________________    __________    ____________    ______

    'xASL_bids_BIDS2Legacy'      'Function'    [1×2 struct]    true  
    'ExploreASL_Master'          'Function'    [1×7 struct]    true  
    'xASL_io_ExportVTK'          'Function'    [1×5 struct]    true  
    'xASL_test_GetLogContent'    'Function'    [1×2 struct]    true  
    'xASL_io_Nifti2Im'           'Function'    [1×1 struct]    true  
    'xASL_tsvRead'               'Function'    [1×2 struct]    true  
    'xASL_tsvWrite'              'Function'    [1×2 struct]    true  

================================================================================
```

2021-05-17 11:55 UTC, MichaelStritt commented on Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
> +    [Fpath, Ffile, Fext] = fileparts(x.DataParPath);
## GE Datasets FlavorDatabase

[logContent.xlsx](https://github.com/ExploreASL/ExploreASL/files/6493551/logContent.xlsx)

### Check the BIDS conversion
`Different value: BIDSVersion (1.6.0 vs 1.5.0)`

2021-05-17 11:57 UTC, MichaelStritt approved these changes
I only re-tested GE and the UnitTests. All of that seems fine for me. 👍

2021-05-17 12:49 UTC, MichaelStritt commented
### GE_PCASL_3Dspiral_volunteer

Re-tested, works fine 👍

2021-05-17 13:58 UTC, merged