Bug #630 population folder
ExploreASL/ExploreASL pull request #648
Opened 2021-06-14 12:54 UTC by MichaelStritt

### Linked issue

Check out #630

2021-06-14 18:32 UTC, jan-petr approved these changes
Correct reorganization of the code. But it still creates the Population file in the derivatives folder. Was that the problem - created on the correct location but too early? @BeatrizPadrela 

Anyway - I removed the initFileSystem function from ExploreASL_Initialize and moved it only to structural/asl/population module. So this should be now fixed, but Henk should check as well...

2021-06-15 08:59 UTC, HenkMutsaerts requested changes
Yes, you're right, the idea is that the population and its subdirs are only created when needed. So this fix is nice, but even nicer to remove this folder creation out of general files and manage this within the individual wrappers that need these folders to exist. 

The issue was not `xASL_init_FileSystem` but `xASL_init_DefinePaths` I believe, that creates everything upon initialization. Easiest fix for now is to move the contents of `xASL_init_DefinePaths` from line 81 onward (loop of `xASL_adm_CreateDir`) to the start of `ExploreASL_ProcessMaster`.

When data is loaded, it should define the paths, when data is processed (i.e., running `ExploreASL_ProcessMaster`) it should create the folders. Is this the case now, that `ExploreASL_ProcessMaster` is only run when processing is set to true, and this creates the folders?

2021-06-15 10:17 UTC, jan-petr commented on Modules/xASL_module_Population.m
> +if ~xASL_exist(x.D.PopDir)
Yes. Fixed.

2021-06-15 10:24 UTC, jan-petr commented
> Yes, you're right, the idea is that the population and its subdirs are only created when needed. So this fix is nice, but even nicer to remove this folder creation out of general files and manage this within the individual wrappers that need these folders to exist.
> 
> The issue was not `xASL_init_FileSystem` but `xASL_init_DefinePaths` I believe, that creates everything upon initialization. Easiest fix for now is to move the contents of `xASL_init_DefinePaths` from line 81 onward (loop of `xASL_adm_CreateDir`) to the start of `ExploreASL_ProcessMaster`.
> 
> When data is loaded, it should define the paths, when data is processed (i.e., running `ExploreASL_ProcessMaster`) it should create the folders. Is this the case now, that `ExploreASL_ProcessMaster` is only run when processing is set to true, and this creates the folders?

I agree in principle. `xASL_init_DefinePaths` should not create anything - but this is already fixed by Michael. All directory creation is done in `xASL_init_FileSystem` - this is then called from all modules (ASL, structural, etc.). So it is now indeed only run when the processind modules are run. It might be possible to move all this from these modules to `ExploreASL_ProcessMaster` if needed - but not sure if this wouldn't have any complications.

Anyway - the things already seem to be done according to what we want... Can we merge?

2021-06-17 10:16 UTC, HenkMutsaerts approved these changes
Yes this looks good. If this is tested and works, I'm good and can be merged. I would keep `xASL_init_FileSystem` in the modules for now to keep modularity.

2021-06-17 11:27 UTC, merged