Bug #565 xASL_adm_DeleteFileList symlink
ExploreASL/ExploreASL pull request #667
Opened 2021-06-19 16:03 UTC by HenkMutsaerts

### Linked issue

Closes #565

2021-07-14 09:20 UTC, jan-petr reviewed
Why do we use the delete function instead of calling xASL_delete one by one in the first place? Is that significantly faster?

2021-07-15 11:09 UTC, HenkMutsaerts commented
> Why do we use the delete function instead of calling xASL_delete one by one in the first place? Is that significantly faster?

If you call `delete`, it will delete in one batch, which crashes if you have symbolic links inside the list of which the directory above it was also in the list but is already deleted. So `delete` crashes if you have a list with files that are also linked within a symbolic link folder. This is the case for BASILs output. BASIL outputs each fit iteration in a separate subfolder, and creates a symbolic link to the latest folder, assuming this is the most optimal output.

2021-07-19 09:46 UTC, MichaelStritt commented
@HenkMutsaerts: Should I just check if I can delete a list of files and if that works it's okay? Or does this require more extensive testing?

2021-07-19 12:14 UTC, MichaelStritt requested changes
Removing files seems to work and is fast, but the file list that is returned is empty?

```matlab
>> pathTest = '.\testFolderToRemove';
>> testFiles = xASL_adm_GetFsList(pathTest, '^.+\.exe$');
>> testFiles

testFiles =

  1×8 cell array

    {'myFile (1).exe'}    {'myFile (2).exe'}    {'myFile (3).exe'}    {'myFile (4).exe'}    
    {'myFile (5).exe'}    {'myFile (6).exe'}    {'myFile (7).exe'}    {'myFile (8).exe'}

>> removedFiles = xASL_adm_DeleteFileList(pathTest, '^.+\.exe$');
>> removedFiles

removedFiles =

  0×0 empty char array
```

2021-07-19 19:17 UTC, jan-petr commented
> > Why do we use the delete function instead of calling xASL_delete one by one in the first place? Is that significantly faster?
> 
> If you call `delete`, it will delete in one batch, which crashes if you have symbolic links inside the list of which the directory above it was also in the list but is already deleted. So `delete` crashes if you have a list with files that are also linked within a symbolic link folder. This is the case for BASILs output. BASIL outputs each fit iteration in a separate subfolder, and creates a symbolic link to the latest folder, assuming this is the most optimal output.

Yes. I understand why `delete` crashes. But I don't understand why we have the try-catch statement with catch calling xASL_delete one by one - why don't we skip the use of `delete` and delete only using the `xASL_delete` in the catch branch - would that be so slower?

I am simply looking for the motivation to try lines 66-67 and not going right away for solution on line 68-79? Is that faster?

2021-07-19 20:32 UTC, HenkMutsaerts commented
Yes, delete is faster, that was the only motivation for the try

2021-07-22 19:12 UTC, jan-petr commented
> Yes, delete is faster, that was the only motivation for the try

OK. That's a satisfactory answer :)

2021-07-22 19:12 UTC, jan-petr approved these changes
OK.

2021-07-22 19:53 UTC, MichaelStritt commented
## Develop

### Test without space in path

```
>> pathTest = '.\Server_xASL\sdfsdf';
>> filepaths = xASL_adm_DeleteFileList(pathTest, '^.+$');
>> filepaths
filepaths =
  4×1 cell array
    {'.\Server_xASL\sdfsdf\Git-2.32.0-64-bit - Kopie (2).exe'    }
    {'.\Server_xASL\sdfsdf\Git-2.32.0-64-bit - Kopie - Kopie.exe'}
    {'.\Server_xASL\sdfsdf\Git-2.32.0-64-bit - Kopie.exe'        }
    {'.\Server_xASL\sdfsdf\Git-2.32.0-64-bit.exe'                }
```

### Test with space in path

```
>> pathTest = '.\Server_xASL\sdf sdf';
>> filepaths = xASL_adm_DeleteFileList(pathTest, '^.+$');
>> filepaths
filepaths =
  4×1 cell array
    {'.\sdf sdf\Git-2.32.0-64-bit - Kopie (2).exe'    }
    {'.\Server_xASL\sdf sdf\Git-2.32.0-64-bit - Kopie - Kopie.exe'}
    {'.\Server_xASL\sdf sdf\Git-2.32.0-64-bit - Kopie.exe'        }
    {'.\Server_xASL\sdf sdf\Git-2.32.0-64-bit.exe'                }
```

## Feature branch

### Test without space in path

```
>> pathTest = '.\Server_xASL\sdfsdf';
>> filepaths = xASL_adm_DeleteFileList(pathTest, '^.+$');
>> filepaths
filepaths =
  0×0 empty char array
```

### Test with space in path

```
>> pathTest = '.\Server_xASL\sdf sdf';
>> filepaths = xASL_adm_DeleteFileList(pathTest, '^.+$');
>> filepaths
filepaths =
  0×0 empty char array
```

## Conclusion

@HenkMutsaerts: Seems like this bug is not in develop and is not related to spaces in file names.

2021-07-22 20:32 UTC, HenkMutsaerts commented
@MichaelStritt can you retest? I indeed reinitialized the output value `filepaths` through the new code, which would then find any residual files to be deleted but this would also render this list empty if the requested files were correctly deleted. Now this behavior is corrected, and another output parameters `pathsNotDeleted` list added for clarity. Is it now working correctly at your end?

2021-07-23 08:30 UTC, MichaelStritt approved these changes
Seems to work now 👍 

```
>> pathWithoutSpaces = '.\Server_xASL\testtest';
>> [deletedFiles,NotDeletedFiles] = xASL_adm_DeleteFileList(pathWithoutSpaces, '^.+$')

deletedFiles =

  4×1 cell array

    {'.\Server_xASL\testtest\Git-2.32.0-64-bit - Kopie (2).exe'    }
    {'.\Server_xASL\testtest\Git-2.32.0-64-bit - Kopie - Kopie.exe'}
    {'.\Server_xASL\testtest\Git-2.32.0-64-bit - Kopie.exe'        }
    {'.\Server_xASL\testtest\Git-2.32.0-64-bit.exe'                }

NotDeletedFiles =
  0×0 empty char array
```

```
>> pathWithSpaces = '.\Server_xASL\test test';
>> [deletedFiles,NotDeletedFiles] = xASL_adm_DeleteFileList(pathWithSpaces, '^.+$')

deletedFiles =
  4×1 cell array

    {'.\Server_xASL\test test\Git-2.32.0-64-bit - Kopie (2).exe'    }
    {'.\Server_xASL\test test\Git-2.32.0-64-bit - Kopie - Kopie.exe'}
    {'.\Server_xASL\test test\Git-2.32.0-64-bit - Kopie.exe'        }
    {'.\Server_xASL\test test\Git-2.32.0-64-bit.exe'                }


NotDeletedFiles =
  0×0 empty char array
```

2021-07-23 08:55 UTC, MichaelStritt requested changes
So the deleted files list seems to work, the other one seems to be bugged though. Check out my UnitTest. You should be able to run it pretty easily.

2021-07-26 08:03 UTC, MichaelStritt commented on Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
> +rmdir(fullfile(TestRepository,'UnitTesting','working_directory','dir with spaces'), 's');
shouldn't be necessary, the basic folder structure should be there if the testing repository is there

2021-07-26 08:06 UTC, MichaelStritt commented on Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
> +mkdir(fullfile(TestRepository,'UnitTesting','working_directory'),'dir with spaces');
Good idea

2021-07-26 08:07 UTC, MichaelStritt commented on Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
> +% Create six test files in test directory
No, it should be six files? Three txt files and three json files.

2021-07-26 08:08 UTC, MichaelStritt commented on Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
> +%% Test run 1
You can define multiple tests so there are multiple runs of one function which is being tested.

2021-07-26 08:27 UTC, MichaelStritt commented on Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
> +mkdir(fullfile(TestRepository,'UnitTesting','working_directory'),'dir with spaces');
b87f04a

2021-07-26 08:29 UTC, MichaelStritt approved these changes
Sorry, I should have read the header more carefully. I thought `pathsNotDeleted` would be the paths in the directory that weren't deleted. You describe it correctly though 👍

2021-07-26 08:32 UTC, merged