Closes #984 General population based report
ExploreASL/ExploreASL pull request #985
Opened 2021-12-09 10:35 UTC by MichaelStritt

### Linked issue

Check out #984

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

2021-12-12 10:55 UTC, HenkMutsaerts commented
Nice idea! Let's discuss. We already have the single-page report, which is intertwined with the QC output, I would continue this work for the multi-page report. And we should try to see if we can use functions that don't require a GUI (very important) and don't require java virtual machine(nice to have but probably very tricky)

2021-12-13 07:38 UTC, MichaelStritt commented
> Nice idea! Let's discuss. We already have the single-page report, which is intertwined with the QC output, I would continue this work for the multi-page report. And we should try to see if we can use functions that don't require a GUI (very important) and don't require java virtual machine(nice to have but probably very tricky)

Don't know why you're talking about GUIs and java, I only used Matlabs `publish` method.

2021-12-13 10:08 UTC, HenkMutsaerts requested changes
Consider using `x.Output` and `x.Output_im`

2021-12-13 10:08 UTC, HenkMutsaerts commented on Functions/xASL_report_Main.m
> +    cd(populationDir);
`pathOriginal = pwd;`
`cd(x.P.PopDir);`

2021-12-13 10:08 UTC, HenkMutsaerts commented on Functions/xASL_report_Main.m
> +    populationDir = fullfile(x.dir.xASLDerivatives, 'Population');
this already existed also in `x.P.PopDir` or something

2021-12-13 10:08 UTC, HenkMutsaerts commented on Functions/xASL_report_Main.m
> +
`cd(pathOriginal);`

2021-12-13 10:08 UTC, HenkMutsaerts commented on Functions/xASL_report_Main.m
> +    if isfield(x,'Version')
Replace by loop,
PrintFields = {'Version', 'Settings;Quality', '...};

2022-01-24 18:26 UTC, HenkMutsaerts commented
> > Nice idea! Let's discuss. We already have the single-page report, which is intertwined with the QC output, I would continue this work for the multi-page report. And we should try to see if we can use functions that don't require a GUI (very important) and don't require java virtual machine(nice to have but probably very tricky)
> 
> Don't know why you're talking about GUIs and java, I only used Matlabs `publish` method.

Matlab has Figure/graphic-creating functions that requires that you run the GUI (they won't run when running Matlab -nodesktop). Then Matlab also has several functions running through the JVM, which you ideally want to skip (it can be buggy sometimes).

2023-05-17 12:29 UTC, closed without merging